### ISSUE TITLE
Still cannot obtain the paper result of hotdog plate

### ISSUE THREAD

**Issue by Epsilon404** [ashmrz/LaTeRF#2]
Hi, I tried to increase the "clip_weight" from `0.01` to `0.02`, `0.05`, `0.1`, `0.5`, `1`, also try to change the "clf_weight" to `0.01`, `0.05` and `0.1`.
And use the original NeRF to train for `10,000` iterations (the result is the same when training for `100,000` iterations), but all the results are still stucking at here:
![image](https://user-images.githubusercontent.com/94212652/205635448-5e647fa5-2b3d-4873-ad23-be0ce4115f88.png)
It looks like the intermediate results, but shows no sign of moving towards an empty plate results like in the paper.
![image](https://user-images.githubusercontent.com/94212652/205639659-8dbbf417-91d2-473a-87d3-94518d37fda9.png)
How to solve the problem to get the results in paper?

**Comment by hugoycj** [comment]
@ashmrz

**Comment by ashmrz** [comment]
Hi! Thanks for getting in touch, and sorry for the late reply. As I mentioned, the original implementation was using the originall NeRF, and this was meant to help with faster convergence (by the use of Instant-NGP + DS-NeRF). I'll work on cleaning the original code base, although it takes 8-10 hourse per scene to converge, and release that one as soon as possiible. In the meanwhile, I appreciate your patience.
